require: sudo
language: node_js
node_js:
  - 6
services:
  - docker
env:
  - DOCKER_IMAGE=prodest/api-detran:${TRAVIS_COMMIT:0:7}
script: 
  - scripts/travis.sh
deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh api api api-detran
  on:
    branch: master
